//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book_info()
        {
            this.status = "Unpaid";
            this.paypal_info = new HashSet<paypal_info>();
            this.transfer_info = new HashSet<transfer_info>();
        }
    
        public string bookCode { get; set; }
        public int tourID { get; set; }
        public int buyerID { get; set; }
        public string paymentMethod { get; set; }
        public string status { get; set; }
        public string passenger { get; set; }
        public decimal totalPrice { get; set; }
    
        public virtual tour_info tour_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<paypal_info> paypal_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transfer_info> transfer_info { get; set; }
        public virtual user_info user_info { get; set; }
    }
}
