//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class gaefa_transfer_new
    {
        public int paymentCode { get; set; }
        public string bookCode { get; set; }
        public System.DateTime paymentDate { get; set; }
        public string senderName { get; set; }
        public decimal amountTransferred { get; set; }
        public string bankName { get; set; }
        public string accountNumber { get; set; }
        public string fromBank { get; set; }
        public Nullable<System.DateTime> approveDate { get; set; }
        public string email { get; set; }
        public string receipt { get; set; }
    
        public virtual gaefa_book_new gaefa_book_new { get; set; }
    }
}
