//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class gaefa_book_new
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gaefa_book_new()
        {
            this.gaefa_paypal_new = new HashSet<gaefa_paypal_new>();
            this.gaefa_pic_info = new HashSet<gaefa_pic_info>();
            this.gaefa_transfer_new = new HashSet<gaefa_transfer_new>();
        }
    
        public string bookCode { get; set; }
        public string email { get; set; }
        public System.DateTime dateToGo { get; set; }
        public string orderReference { get; set; }
        public System.DateTime dateOrder { get; set; }
        public int tourID { get; set; }
        public string paymentMethod { get; set; }
        public string status { get; set; }
        public int childCount { get; set; }
        public int adultCount { get; set; }
        public int childNoBedCount { get; set; }
        public int passengerAmount { get; set; }
        public decimal totalPrice { get; set; }
        public string note { get; set; }
        public string couponCode { get; set; }
        public string promoCode { get; set; }
        public bool postedToGaefa { get; set; }
        public bool postedPassenger { get; set; }
    
        public virtual gaefa_coupon gaefa_coupon { get; set; }
        public virtual gaefa_promo gaefa_promo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gaefa_paypal_new> gaefa_paypal_new { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gaefa_pic_info> gaefa_pic_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gaefa_transfer_new> gaefa_transfer_new { get; set; }
    }
}
