//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class gaefa_coupon
    {
        public int id { get; set; }
        public string couponCode { get; set; }
        public Nullable<int> packMin { get; set; }
        public Nullable<decimal> priceMin { get; set; }
        public System.DateTime expiryDate { get; set; }
        public System.DateTime availableDate { get; set; }
        public bool status { get; set; }
        public Nullable<System.DateTime> usedDate { get; set; }
        public Nullable<int> discPercentage { get; set; }
        public Nullable<decimal> discPrice { get; set; }
    }
}
